import type { Metadata } from "next";
import { NextIntlClientProvider, useMessages } from 'next-intl';
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { HeaderV2 } from "@/components/header-v2";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = useMessages();
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlClientProvider messages={messages}>
          <HeaderV2 />
          {children}
        </NextIntlClientProvider></body>
    </html>
  );
}
